Update Absolute Series Scanner.py
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/335
Will use this bug report to summarize all known issues:

Directory "I:\动漫" - https://github.com/ZeroQI/Absolute-Series-Scanner/issues/335
```
File "F:\Plex\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 559, in Scan
    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id").encode('utf-8'), root.encode('utf-8'), path.encode('utf-8'), len(files or []), len(dirs or [])))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 3: ordinal not in range(128)
```

Library name "Anime 🇯🇵"- https://github.com/ZeroQI/Absolute-Series-Scanner/issues/306
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 554, in Scan
    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id"), root, path, len(files or []), len(dirs or [])))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-9: ordinal not in range(128)

path '/volume4/Video/sorted/HD Cartoon Series/2x2/Кит Stupid Show/Season01/КитStupidShowS01E01.mp4' - https://github.com/ZeroQI/Absolute-Series-Scanner/issues/276
```
File "/volume3/Plex/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 559, in Scan
    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id").encode('utf-8'), root.encode('utf-8'), path.encode('utf-8'), len(files or []), len(dirs or [])))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 15: ordinal not in range(128)
```

Source: https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte
- Unicode strings do not contain any encoding but Unicode point codes, can be encoded to strings
- Strings contain encoded text (UTF-8, UTF-16, ISO-8895-1, GBK, Big5 etc...), can be decoded to Unicode, Files and text data are always transferred in encoded strings.

**Since the scanner crashed, i would have to move the folder out, rescan, move it back, rescan at each attempt (the pain of scanner development)**

path.encode('utf-8'): UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
path.decode('utf-8'): UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 3: ordinal not in range(128)
path.decode('ascii', 'replace'): UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

OK let's catch errors and revert to working for this path "动漫" line 559-560
```
  try:                    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id"), root, path, len(files or []), len(dirs or [])))
  except Exception as e:  Log.info('exception: {}'.format(e))
```

That work back, good. Need to test the others without breaking this one
- 'Кит Stupid Show/Season01/КитStupidShowS01E01.mp4' work back after ".decode('utf-8')" on filename
- "Anime 🇯🇵" works after putting log in try-except but root logs catch exception, ok after ".encode('utf-8')"
- weirdly enough the library name is correct in one series, in the other one it shows as Library: 'Anime 馃嚡馃嚨'...