Crash fixes
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/172
Episodes need at least a default offset entry of '0' otherwise a KeyError will be hit.
-------------------------
    cumulative_offset = sum( [ AniDB_op [ ANIDB_RX.index(rx) ][x] for x in Dict(AniDB_op, ANIDB_RX.index(rx), default={0:0}) if x<ep ] )
KeyError: (2,)
-------------------------
If a regex other than an op/en is matched, the 'ep_' variable is not known so it need to be updating the 'ep' variable instead of creating a new one.
-------------------------
    add_episode_into_plex(media, file, root, path, show, int(season), int(ep_), title, year, int(ep2) if ep2 and ep2.isdigit() else int(ep_), rx, tvdb_mapping, unknown_series_length, offset_season, offset_episode, mappingList)
UnboundLocalError: local variable 'ep_' referenced before assignment
-------------------------