Fix IGNORE_DIRS_RX loop
Issue in removal of root from string as subdir string is no longer found in the list to remove.

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 642, in Scan
    Scan(os.path.relpath(subdir,root), sorted(subdir_files), [], sorted(subdir_subdirs), root=root, plex_entries=plex_entries, is_grouping_scan=is_grouping_scan)
  File "C:\Users\xxx\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 325, in Scan
    if re.match(rx, os.path.basename(subdir), re.IGNORECASE): subdirs.remove(subdir);  Log.info("\"%s\" match IGNORE_DIRS_RX: \"%s\"" % (subdir, rx));  break  #skip dirs to be ignored
ValueError: list.remove(x): x not in list