m
Issue introduced in https://github.com/ZeroQI/Absolute-Series-Scanner/commit/9f4e152e02627044b644bcb386107fb979d836a4
File "C:\Users\sling\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 75, in <module>
    MOVIE_RX        = cic(r'(^|(?P<show>.*) (?P<year>\d{4})$')
[...]
error: unbalanced parenthesis

https://github.com/ZeroQI/Absolute-Series-Scanner/issues/334