Log output converted to unicode string fix
May 03, 2021 22:33:10.745 [12192] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 1117, in Scan
    for entry in standard_holding + unknown_holding:  add_episode_into_plex(media, *entry)
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 393, in add_episode_into_plex
    if not os.path.exists(file):  file = os.path.join(root, path, file)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/python27.zip/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 71: ordinal not in range(128)