Exception: 'invalid literal for int() with base 10: '''
Issue was is using 'default' on 'get()'. If the entry exists but is blank, it would not use the default. So moved from default usage to simple 'or' test to catch a 'None' or blank return.