Binhex arch-plex Docker container libxslt library missing fix
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/204
Using the latest binhex plexpass docker returns: https://github.com/binhex/arch-plex

Error in Python: Looking up module:
Traceback (most recent call last):
File "/config/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 20, in 
from lxml import etree # fromstring
ImportError: libexslt.so.0: cannot open shared object file: No such file or directory

Using the latest binhex plexstandard docker returns: https://github.com/binhex/arch-plex

Error in Python: Looking up module:
Traceback (most recent call last):
File "/config/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 20, in 
from lxml import etree # fromstring
ImportError: libexslt.so.0: cannot open shared object file: No such file or directory

Using the limetech docker (unraid default) returns: https://github.com/limetech/dockerapp-plex
expected results.

Issue appears to be in the binhex repositories. All repos are pulling plex 1.15.* .
Opening the dockers terminal and running "pacman -S libxslt --noconfirm" then rebooting the docker fixs the issue.

Thanks Hiren-Z  for tenacity and tests which allowed binhex to provide the command confirmed back to fix all issues by Hiren-Z
Good teamwork guys!